version: '3'

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: web.Dockerfile
    container_name: nginx_cp
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "tomcat"

  app:
    build:
      context: ./application
      dockerfile: application.Dockerfile
    container_name: app_cp
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - /var/lib/docker/volumes/application/_data:/opt

  tomcat:
    build:
      context: ./tomcat
      dockerfile: tomcat.Dockerfile
    container_name: tomcat_cp
    volumes:
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - /var/lib/docker/volumes/application/_data:/usr/share/tomcat/webapps
